import {
  Sport,
  SkillLevel,
  UserGender,
  MatchGenderRequirement,
  UserProfile,
  MatchRoom,
} from './types';

export const ALL_SPORTS: Sport[] = [
  '羽球',
  '籃球',
  '網球',
  '足球',
  '排球',
  '跑步',
];
export const SKILL_LEVELS: SkillLevel[] = [
  '初學',
  '初階',
  '中階',
  '進階',
  '選手等級',
];
export const USER_GENDERS: UserGender[] = ['男性', '女性'];
export const MATCH_GENDER_REQUIREMENTS: MatchGenderRequirement[] = [
  '不限',
  '男性',
  '女性',
];
export const COST_TO_CREATE = 10;
export const COST_TO_JOIN = 5;
export const COINS_PER_RATING = 2;
export const MONTHLY_COINS = { free: 20, subscribed: 200 };

export const TAIWAN_DISTRICTS: Record<string, string[]> = {
  台北市: [
    '中正區',
    '大同區',
    '中山區',
    '松山區',
    '大安區',
    '萬華區',
    '信義區',
    '士林區',
    '北投區',
    '內湖區',
    '南港區',
    '文山區',
  ],
  新北市: [
    '板橋區',
    '三重區',
    '中和區',
    '永和區',
    '新莊區',
    '新店區',
    '樹林區',
    '鶯歌區',
    '三峽區',
    '淡水區',
    '汐止區',
    '瑞芳區',
    '土城區',
    '蘆洲區',
    '五股區',
    '泰山區',
    '林口區',
    '深坑區',
    '石碇區',
    '坪林區',
    '三芝區',
    '石門區',
    '八里區',
    '平溪區',
    '雙溪區',
    '貢寮區',
    '金山區',
    '萬里區',
    '烏來區',
  ],
  桃園市: [
    '桃園區',
    '中壢區',
    '大溪區',
    '楊梅區',
    '蘆竹區',
    '大園區',
    '龜山區',
    '八德區',
    '龍潭區',
    '平鎮區',
    '新屋區',
    '觀音區',
    '復興區',
  ],
  新竹市: ['東區', '北區', '香山區'],
  新竹縣: [
    '竹北市',
    '竹東鎮',
    '新埔鎮',
    '關西鎮',
    '湖口鄉',
    '新豐鄉',
    '芎林鄉',
    '橫山鄉',
    '北埔鄉',
    '寶山鄉',
    '峨眉鄉',
    '尖石鄉',
    '五峰鄉',
  ],
  台中市: [
    '中區',
    '東區',
    '南區',
    '西區',
    '北區',
    '北屯區',
    '西屯區',
    '南屯區',
    '太平區',
    '大里區',
    '霧峰區',
    '烏日區',
    '豐原區',
    '后里區',
    '石岡區',
    '東勢區',
    '和平區',
    '新社區',
    '潭子區',
    '大雅區',
    '神岡區',
    '大肚區',
    '沙鹿區',
    '龍井區',
    '梧棲區',
    '清水區',
    '大甲區',
    '外埔區',
    '大安區',
  ],
  台南市: [
    '中西區',
    '東區',
    '南區',
    '北區',
    '安平區',
    '安南區',
    '永康區',
    '歸仁區',
    '新化區',
    '左鎮區',
    '玉井區',
    '楠西區',
    '南化區',
    '仁德區',
    '關廟區',
    '龍崎區',
    '官田區',
    '麻豆區',
    '佳里區',
    '西港區',
    '七股區',
    '將軍區',
    '學甲區',
    '北門區',
    '新營區',
    '後壁區',
    '白河區',
    '東山區',
    '六甲區',
    '下營區',
    '柳營區',
    '鹽水區',
    '善化區',
    '大內區',
    '山上區',
    '新市區',
    '安定區',
  ],
  高雄市: [
    '楠梓區',
    '左營區',
    '鼓山區',
    '三民區',
    '鹽埕區',
    '前金區',
    '新興區',
    '苓雅區',
    '前鎮區',
    '旗津區',
    '小港區',
    '鳳山區',
    '林園區',
    '大寮區',
    '大樹區',
    '大社區',
    '仁武區',
    '鳥松區',
    '岡山區',
    '橋頭區',
    '燕巢區',
    '田寮區',
    '阿蓮區',
    '路竹區',
    '湖內區',
    '茄萣區',
    '永安區',
    '彌陀區',
    '梓官區',
    '旗山區',
    '美濃區',
    '六龜區',
    '甲仙區',
    '杉林區',
    '內門區',
    '茂林區',
    '桃源區',
    '那瑪夏區',
  ],
};
export const TAIWAN_CITIES = Object.keys(TAIWAN_DISTRICTS);

export const MOCK_USERS: UserProfile[] = [
  {
    id: 'user-1',
    name: '陳浩南',
    skillLevels: { 籃球: '進階', 足球: '進階' },
    gender: '男性',
    birthDate: '1995-05-20',
    city: '台北市',
    district: '信義區',
    ratings: {
      intensity: { 籃球: [4, 5] },
      friendliness: [5, 5],
      comments: [
        { fromUserId: 'user-2', text: '打球很罩！' },
        { fromUserId: 'user-4', text: '非常有風度' },
      ],
    },
    friends: ['user-2'],
    friendRequests: [{ from: 'user-3', status: 'pending' }],
    conversations: {
      system: {
        participantIds: ['system', 'user-1'],
        messages: [
          {
            id: 'msg-reward-1',
            fromUserId: 'system',
            text: '這是您本月的訂閱者獎勵！',
            timestamp: new Date().toISOString(),
            isRead: false,
            reward: { amount: 200, claimed: false },
          },
        ],
      },
      'user-2': {
        participantIds: ['user-1', 'user-2'],
        messages: [
          {
            id: 'msg-convo-1',
            fromUserId: 'user-2',
            text: '週末要不要一起打球？',
            timestamp: new Date(Date.now() - 86400000).toISOString(),
            isRead: true,
          },
        ],
      },
    },
    wCoins: 150,
    subscriptionTier: 'subscribed',
    monthlyActivity: {
      lastReset: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000).toISOString(),
    },
  },
  {
    id: 'user-2',
    name: '山雞',
    skillLevels: { 羽球: '中階' },
    gender: '男性',
    birthDate: '1996-08-15',
    city: '新北市',
    district: '板橋區',
    ratings: {
      intensity: { 籃球: [3] },
      friendliness: [4],
      comments: [{ fromUserId: 'user-1', text: 'nice player' }],
    },
    friends: ['user-1', 'user-4'],
    friendRequests: [],
    conversations: {
      'user-1': {
        participantIds: ['user-1', 'user-2'],
        messages: [
          {
            id: 'msg-convo-1',
            fromUserId: 'user-2',
            text: '週末要不要一起打球？',
            timestamp: new Date(Date.now() - 86400000).toISOString(),
            isRead: false,
          },
        ],
      },
    },
    wCoins: 50,
    subscriptionTier: 'free',
    monthlyActivity: { lastReset: new Date().toISOString() },
  },
  {
    id: 'user-3',
    name: '小結巴',
    skillLevels: { 網球: '初階', 跑步: '中階' },
    gender: '女性',
    birthDate: '2000-03-10',
    city: '桃園市',
    district: '桃園區',
    ratings: {
      intensity: { 網球: [2], 跑步: [3] },
      friendliness: [5],
      comments: [],
    },
    friends: [],
    friendRequests: [],
    conversations: {},
    wCoins: 20,
    subscriptionTier: 'free',
    monthlyActivity: { lastReset: new Date().toISOString() },
  },
  {
    id: 'user-4',
    name: '丁瑤',
    skillLevels: { 羽球: '選手等級', 網球: '進階' },
    gender: '女性',
    birthDate: '1985-11-22',
    city: '台北市',
    district: '大安區',
    ratings: {
      intensity: { 羽球: [5, 5] },
      friendliness: [3, 4],
      comments: [{ fromUserId: 'user-2', text: '實力堅強！' }],
    },
    friends: ['user-2'],
    friendRequests: [],
    conversations: {},
    wCoins: 500,
    subscriptionTier: 'subscribed',
    monthlyActivity: { lastReset: new Date().toISOString() },
  },
];

export const MOCK_ROOMS: MatchRoom[] = [
  {
    id: 'room-1',
    host: MOCK_USERS[0],
    sport: '籃球',
    locationName: '台北市青年公園籃球場',
    time: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    maxPlayers: 6,
    currentPlayers: [MOCK_USERS[0], MOCK_USERS[1]],
    skillLevel: '進階',
    genderRequirement: '不限',
    messages: [
      {
        userId: 'user-1',
        name: '陳浩南',
        text: '晚上有人要來鬥牛嗎?',
        timestamp: new Date(Date.now() - 60000).toISOString(),
      },
      {
        userId: 'user-2',
        name: '山雞',
        text: '我會到!',
        timestamp: new Date(Date.now() - 30000).toISOString(),
      },
    ],
  },
  {
    id: 'room-2',
    host: MOCK_USERS[3],
    sport: '羽球',
    locationName: '板橋運動中心羽球場',
    time: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    maxPlayers: 4,
    currentPlayers: [MOCK_USERS[3]],
    skillLevel: '進階',
    genderRequirement: '不限',
    messages: [],
    notes: '場地費均攤，大約每人100元。請自備球拍。',
  },
  {
    id: 'room-3',
    host: MOCK_USERS[2],
    sport: '網球',
    locationName: '林口運動公園網球場',
    time: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    maxPlayers: 4,
    currentPlayers: [MOCK_USERS[2], MOCK_USERS[0], MOCK_USERS[1]],
    skillLevel: '初階',
    genderRequirement: '不限',
    messages: [],
  },
  {
    id: 'room-4',
    host: MOCK_USERS[2],
    sport: '跑步',
    locationName: '大安森林公園',
    time: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    maxPlayers: 10,
    currentPlayers: [MOCK_USERS[2]],
    skillLevel: '中階',
    genderRequirement: '不限',
    messages: [],
  },
];
